### PR TITLE
Add py.typed file to mark package as annotated (PEP 561)

### PR DESCRIPTION
**Pull request by HarrySky**
At the moment `mypy` tool will give error below, because there is no `py.typed` file inside package. AFAIK bidict is annotated (:tada:), so why not add this file? See [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information) for details

```
error: Skipping analyzing 'bidict': found module but no type hints or library stubs  [import]
```

### CODE REVIEW

**Comment by jab** [comment]
Merged and released in [v0.21.1](https://bidict.readthedocs.io/en/v0.21.1/changelog.html).

[Thanks](https://bidict.readthedocs.io/en/v0.21.1/thanks.html), @HarrySky!

**Comment by jab** [comment]
UPDATE: It turns out dad5f3c6f38aa8cd77ab5f29691c9fa833050dc1 was missing some required changes to setup.py (namely, adding `package_data={'bidict': ['py.typed']}`), which caused the py.typed file to end up not getting installed. I've yanked the v0.21.1 release and fixed this in [v0.21.2](https://bidict.readthedocs.io/en/v0.21.2/changelog.html).

**Comment by HarrySky** [comment]
@jab that's strange, I added it to MANIFEST.in, in other projects it works without modifying setup.py🙈

**Comment by HarrySky** [comment]
@jab found a problem - there is no `include_package_data=True` argument passed to `setup()` in setup.py

**Comment by jab** [comment]
Switched in e69ff40. Thanks, @HarrySky!

**Pull request closed without merging**
